### ISSUE TITLE
NameError: name 'key' is not defined

### ISSUE THREAD

**Issue by wiseaidev** [atolab/zenoh-python#2]
Hi everyone,
i want to report that there is problem with zenoh class, so if i want to create a zenoh object that has a session  and use that session to open a zenoh-net session it works fine if the key is user, 
z = Zenoh.login(locator,{'user': b'123456789'})
but if we change it to z = Zenoh.login(locator,{'pass': b'123456789'})
it will throw a NameError.
key should be k in your code.
finally, why i can't create a session with my own credentials?, and why there is two classes zenoh.Zenoh and zenoh.net??
it seems like you have begin in developing zenoh and then switch to zenoh.net
Something is wrong with zenoh package. because i cant use the function admin() under the zenoh object, if i use it it does nothing in creating backends, storages...
sorry for my language.
regards,
Harmouch,Mahmoud
![Screenshot from 2020-03-18 14-50-51](https://user-images.githubusercontent.com/62179149/76962431-e67fd600-6927-11ea-99f3-101ddc0de458.png)

**Comment by JEnoch** [comment]
Hi @Harmouch101 ,

Thanks for reporting this bug! I just pushed a fix for this.

> why i can't create a session with my own credentials

The credentials must be configured in the zenohd router via a simple text file listing the user/password.
See https://github.com/atolab/zenoh/blob/master/etc/passwd as an example.
Then you can start the zenohd router using the -u option to pass this file:
`$> ./zenohd.exe-u etc/passwd`

> why there is two classes zenoh.Zenoh and zenoh.net??
> it seems like you have begin in developing zenoh and then switch to zenoh.net

Actually, that's the opposite:
We started to develop the zenoh as a protocol, and on top of that a geo-distributed storage and query infrastructure in the [Yaks](https://github.com/atolab/yaks) project.
Recently, as both Zenoh and Yaks were selected by the Eclipse Foundation to part of the [Eclipse IoT group](https://iot.eclipse.org/) we decided it was a better idea to merge the both project under the same **Eclipse zenoh** banner.
As a consequence, the former zenoh project became the zenoh-net API within Eclipse zenoh. And it is still usable as such by user wanting to experiment directly with the protocol.
And the former Yaks project became the principale API of Eclipse zenoh.

To sumarize:
- **zenoh.Zenoh** is the main API of the zenoh project
- **zenoh.net** is a more "advanced" API allowing to experiment directly with the protocol used internally by the zenoh project.

> Something is wrong with zenoh package. because i cant use the function admin() under the zenoh object, if i use it it does nothing in creating backends, storages...

Could you please detail your problems with the admin() function in a new issue, or come for a direct chat on our [Gitter channel](https://gitter.im/atolab/zenoh).
