### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by wiseaidev** [atolab/zenoh-python#4]
hi,
i just noticed a naming error, i know that the function is private but it is better to correct the syntax , maybe this error occurs because of the programming laziness lol...
![Screenshot from 2020-03-20 11-33-14](https://user-images.githubusercontent.com/62179149/77152245-3da8b680-6aa0-11ea-9925-f8eb1c5e402f.png)
so time should be timestamp
because of coronavirus covid-19, i am reviewing your code and correct it for free lol
best regards,

**Comment by JEnoch** [comment]
Hi @Harmouch101 ,

Thanks for your issues reports!
As you may know, our zenoh project is now an Eclipse open-source project in incubation status:
https://projects.eclipse.org/projects/iot.zenoh

As a consequence, all the zenoh repositories are migrating under https://github.com/eclipse-zenoh/ . 
I suggest you rather open issues in those repositories. For zenoh-python: https://github.com/eclipse-zenoh/zenoh-python/issues . 
I already copied and fixed your issue #2 as eclipse-zenoh/zenoh-python#1

As you noticed, we didn't put so much effort in the Python API of zenoh yet 😜 .
We rather focused on the zenoh core (i.e. the router) which was developed in OCaml, but that we are currently re-writing in RUST.

If you have some time and would like to contribute to the Eclipse zenoh Python API (or any other part of zenoh), you're really welcome!
All you would have to do is:

1. Sign the Eclipse Contribution Agreement, as described in https://github.com/eclipse-zenoh/zenoh-python/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement
2. Fork the https://github.com/eclipse-zenoh/zenoh-python repository
3. Do pull requests for your contributions and/or fixes of issues (described in https://github.com/eclipse-zenoh/zenoh-python/issues)

Once you have done that we can review the PR and accept your contributions.
You can also update the https://github.com/eclipse-zenoh/zenoh-python/blob/master/CONTRIBUTORS.md file with your name if you wish.

Best regards,
